language: python
services:
  - mysql
  - postgresql
python:
  - "2.7"
  - "3.6"
before_install:
  - mysql -e 'CREATE DATABASE test;'
before_script:
  - psql -c 'create database test;' -U postgres
# command to install dependencies
install:
  - pip install tox
# command to run tests
script:
  - tox
